Update index.mdx
The way the docs recommend to import prisma causes the following error when running build with Vite on a Svelte Kit procject:

import pkg, { PrismaClient } from '@prisma/client';
              ^^^^^^^^^^^^
SyntaxError: Named export 'PrismaClient' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.

FIX: import prisma like this:

import type { PrismaClient } from '@prisma/client'
import Prisma from '@prisma/client'

// add prisma to the NodeJS global type
interface CustomNodeJsGlobal extends NodeJS.Global {
    prisma: PrismaClient
}

// Prevent multiple instances of Prisma Client in development
declare const global: CustomNodeJsGlobal

const prisma = global.prisma || new Prisma.PrismaClient()

if (process.env.NODE_ENV === 'development') {
    global.prisma = prisma
}